//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFContpaq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administradores
    {
        public int AdminID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Departamento { get; set; }
        public string Email { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public bool CrearAdmin { get; set; }
        public bool Permisos { get; set; }
        public bool EnviarNotificaciones { get; set; }
        public bool CargarReportes { get; set; }
        public string Rol { get; set; }
        public bool Bloqueado { get; set; }
        public string ConfirmarPassword { get; set; }
    }
}
