//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFContpaq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reportes
    {
        public int ReporteID { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> FAQ { get; set; }
        public string Sistema { get; set; }
        public string Causa { get; set; }
        public string Problema { get; set; }
        public string Solucion { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
